# Generated by Django 3.2.13 on 2024-01-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_auto_20240125_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotuser',
            name='sentiment_counts',
            field=models.JSONField(default=dict),
        ),
    ]
