# Generated by Django 3.2.13 on 2024-01-26 14:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_alter_chatbotuser_sentiment_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='sentiment_scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='sentiment_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbotuser'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
