# Generated by Django 3.2.13 on 2024-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_auto_20240126_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='sentiment_scores',
            field=models.JSONField(default=dict),
        ),
    ]
