# Generated by Django 3.2.13 on 2024-01-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_alter_userscore_sentiment_scores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='chatbotuser',
            name='sentiment_counts',
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
