# Generated by Django 3.2.13 on 2024-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_auto_20240126_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotuser',
            name='sentiment_counts',
            field=models.JSONField(default=dict),
        ),
    ]
