# Generated by Django 3.2.13 on 2024-01-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_remove_chatbotuser_sentiment_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='sentiment_scores',
        ),
    ]
