# Generated by Django 3.2.13 on 2024-01-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_remove_userscore_sentiment_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotuser',
            name='sentiment_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userscore',
            name='sentiment_scores',
            field=models.JSONField(default=dict),
        ),
    ]
