# Generated by Django 3.2.13 on 2024-01-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_auto_20240126_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userscore', to='chatbot.chatbotuser'),
        ),
    ]
