# Generated by Django 3.2.13 on 2024-01-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_alter_userscore_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotuser',
            name='sentiment_counts',
        ),
        migrations.DeleteModel(
            name='Sentiment',
        ),
    ]
