# Generated by Django 3.2.13 on 2024-01-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0025_auto_20240126_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotuser',
            name='sentiment_counts',
            field=models.JSONField(default=dict, unique=True),
        ),
    ]
