# Generated by Django 3.2.13 on 2024-01-30 15:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0029_alter_userscore_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userscore',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 15, 10, 40, 960588)),
        ),
    ]
