# Generated by Django 3.2.13 on 2024-01-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0030_auto_20240130_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='daily_sentiment_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
