"""Shared core building blocks for SDK v2.

This package is mixed: most modules are implemented, while a few helper modules
remain contract-only during the migration.
"""

from .base import NEKO_PLUGIN_META_ATTR, NEKO_PLUGIN_TAG, NekoPluginBase, PluginMeta
from .config import (
    PluginConfig,
    PluginConfigBaseView,
    PluginConfigProfiles,
)
from plugin.sdk.shared.models.exceptions import (
    ConfigPathError,
    ConfigProfileError,
    ConfigValidationError,
    PluginConfigError,
)
from .decorators import (
    PERSIST_ATTR,
    EntryKind,
    HookDecoratorMeta,
    after_entry,
    around_entry,
    before_entry,
    custom_event,
    hook,
    lifecycle,
    message,
    neko_plugin,
    on_event,
    plugin,
    plugin_entry,
    replace_entry,
    timer_interval,
)
from .context import SdkContext, ensure_sdk_context
from .bus_context import (
    SdkBusContext,
    SdkBusConversationRecord,
    SdkBusDelta,
    SdkBusEventRecord,
    SdkBusLifecycleRecord,
    SdkBusList,
    SdkBusMemoryRecord,
    SdkBusMessageRecord,
    SdkBusWatcher,
    ensure_sdk_bus_context,
)
from .events import EVENT_META_ATTR, EventHandler, EventMeta
from .hook_executor import HookExecutorMixin
from .hooks import HOOK_META_ATTR, HookHandler, HookMeta, HookTiming
from .plugins import (
    InvalidEntryRefError,
    InvalidEventRefError,
    PluginCallError,
    PluginDescriptor,
    Plugins,
    parse_entry_ref,
    parse_event_ref,
)
from .router import EntryConflictError, PluginRouter, PluginRouterError, RouteHandler
from .types import (
    EntryRef,
    EventRef,
    InputSchema,
    JsonObject,
    JsonScalar,
    JsonValue,
    LoggerLike,
    Metadata,
    MutableStateProtocol,
    PluginContextProtocol,
    PluginRef,
)

__all__ = [
    "NEKO_PLUGIN_META_ATTR",
    "NEKO_PLUGIN_TAG",
    "PluginMeta",
    "NekoPluginBase",
    "PluginConfig",
    "PluginConfigError",
    "ConfigPathError",
    "ConfigValidationError",
    "ConfigProfileError",
    "PluginConfigBaseView",
    "PluginConfigProfiles",
    "Plugins",
    "PluginDescriptor",
    "PluginCallError",
    "InvalidEntryRefError",
    "InvalidEventRefError",
    "parse_entry_ref",
    "parse_event_ref",
    "PluginRouter",
    "PluginRouterError",
    "EntryConflictError",
    "RouteHandler",
    "EVENT_META_ATTR",
    "EventMeta",
    "EventHandler",
    "SdkContext",
    "ensure_sdk_context",
    "SdkBusContext",
    "SdkBusMessageRecord",
    "SdkBusEventRecord",
    "SdkBusLifecycleRecord",
    "SdkBusConversationRecord",
    "SdkBusMemoryRecord",
    "SdkBusList",
    "SdkBusWatcher",
    "SdkBusDelta",
    "ensure_sdk_bus_context",
    "HOOK_META_ATTR",
    "HookMeta",
    "HookHandler",
    "HookTiming",
    "HookExecutorMixin",
    "PluginRef",
    "EntryRef",
    "EventRef",
    "PluginContextProtocol",
    "MutableStateProtocol",
    "JsonScalar",
    "JsonValue",
    "JsonObject",
    "Metadata",
    "InputSchema",
    "LoggerLike",
    "EntryKind",
    "HookDecoratorMeta",
    "PERSIST_ATTR",
    "neko_plugin",
    "on_event",
    "plugin_entry",
    "lifecycle",
    "message",
    "timer_interval",
    "custom_event",
    "plugin",
    "hook",
    "before_entry",
    "after_entry",
    "around_entry",
    "replace_entry",
]
